# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - perso_test_thumbs
  - perso_test_vertical
  - perso_test_horizontal
  - peros_test_shaun_the_sheep

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - apk update && apk add libc-dev gcc make
    - make
  artifacts:
    untracked: true
    when: on_success
    expire_in: 20 min

test-nb-relatif:
  stage: test       # s'exécute à l'étape 'test'
  script:
    - mkdir -p out  # on crée le répertoire de sortie
    - ./ppm2jpeg --outfile=./out/invader.jpg ./images/invader.pgm 
    - test -f ./out/invader.jpg # on vérifie que le fichier de sortie existe

test-nb-absolu:
  stage: test       # s'exécute à l'étape 'test'
  script:
    - mkdir -p out  # on crée le répertoire de sortie
    - echo $(pwd)/images/invader.pgm # regardez, un chemin absolu !
    - ./ppm2jpeg --outfile=$(pwd)/out/invader.jpg $(pwd)/images/invader.pgm 
    - test -f ./out/invader.jpg # on vérifie que le fichier de sortie existe

test-couleur-ssech:
  stage: test       # s'exécute à l'étape 'test'
  script:
    - mkdir -p out  # on crée le répertoire de sortie
    - ./ppm2jpeg --outfile=./out/thumbs-2x2-2x1-2x1.jpg --sample=2x2,2x1,2x1 ./images/thumbs.ppm
    - test -f ./out/thumbs-2x2-2x1-2x1.jpg # on vérifie que le fichier de sortie existe

test-ssech-all-thumbs:
  stage: perso_test_thumbs
  script:
    - mkdir -p our_test
    - ./ppm2jpeg --sample=1x1,1x1,1x1 ./images/thumbs.ppm --st
    - test -f ./our_test/thumbs_1x1,1x1,1x1.jpg

    - ./ppm2jpeg --sample=1x2,1x1,1x2 ./images/thumbs.ppm --st
    - test -f ./our_test/thumbs_1x2,1x1,1x2.jpg

    - ./ppm2jpeg --sample=2x1,2x1,2x1 ./images/thumbs.ppm --st
    - test -f ./our_test/thumbs_2x1,2x1,2x1.jpg

    - ./ppm2jpeg --sample=2x2,2x1,2x1 ./images/thumbs.ppm --st
    - test -f ./our_test/thumbs_2x2,2x1,2x1.jpg

    - ./ppm2jpeg --sample=3x1,3x1,3x1 ./images/thumbs.ppm --st
    - test -f ./our_test/thumbs_3x1,3x1,3x1.jpg

    - ./ppm2jpeg --sample=3x2,1x2,1x2 ./images/thumbs.ppm --st
    - test -f ./our_test/thumbs_3x2,1x2,1x2.jpg

test-ssech-all-vertical:
  stage: perso_test_vertical
  script:
    - ./ppm2jpeg --sample=1x1,1x1,1x1 ./images/vertical.ppm --st
    - test -f ./our_test/vertical_1x1,1x1,1x1.jpg

    - ./ppm2jpeg --sample=1x2,1x1,1x2 ./images/vertical.ppm --st
    - test -f ./our_test/vertical_1x2,1x1,1x2.jpg

    - ./ppm2jpeg --sample=2x1,2x1,2x1 ./images/vertical.ppm --st
    - test -f ./our_test/vertical_2x1,2x1,2x1.jpg

    - ./ppm2jpeg --sample=2x2,2x1,2x1 ./images/vertical.ppm --st
    - test -f ./our_test/vertical_2x2,2x1,2x1.jpg

    - ./ppm2jpeg --sample=3x1,3x1,3x1 ./images/vertical.ppm --st
    - test -f ./our_test/vertical_3x1,3x1,3x1.jpg

    - ./ppm2jpeg --sample=3x2,1x2,1x2 ./images/vertical.ppm --st
    - test -f ./our_test/vertical_3x2,1x2,1x2.jpg
  
test-ssech-all-horizontal:
  stage: perso_test_horizontal
  script:
    - ./ppm2jpeg --sample=1x1,1x1,1x1 ./images/horizontal.ppm --st
    - test -f ./our_test/horizontal_1x1,1x1,1x1.jpg

    - ./ppm2jpeg --sample=1x2,1x1,1x2 ./images/horizontal.ppm --st
    - test -f ./our_test/horizontal_1x2,1x1,1x2.jpg

    - ./ppm2jpeg --sample=2x1,2x1,2x1 ./images/horizontal.ppm --st
    - test -f ./our_test/horizontal_2x1,2x1,2x1.jpg

    - ./ppm2jpeg --sample=2x2,2x1,2x1 ./images/horizontal.ppm --st
    - test -f ./our_test/horizontal_2x2,2x1,2x1.jpg

    - ./ppm2jpeg --sample=3x1,3x1,3x1 ./images/horizontal.ppm --st
    - test -f ./our_test/horizontal_3x1,3x1,3x1.jpg

    - ./ppm2jpeg --sample=3x2,1x2,1x2 ./images/horizontal.ppm --st
    - test -f ./our_test/horizontal_3x2,1x2,1x2.jpg
  
test-ssech-all-shaun_the_sheep:
  stage: perso_test_shaun_the_sheep
  script:
    - ./ppm2jpeg --sample=1x1,1x1,1x1 ./images/shaun_the_sheep.ppm --st
    - test -f ./our_test/shaun_the_sheep_1x1,1x1,1x1.jpg

    - ./ppm2jpeg --sample=1x2,1x1,1x2 ./images/shaun_the_sheep.ppm --st
    - test -f ./our_test/shaun_the_sheep_1x2,1x1,1x2.jpg

    - ./ppm2jpeg --sample=2x1,2x1,2x1 ./images/shaun_the_sheep.ppm --st
    - test -f ./our_test/shaun_the_sheep_2x1,2x1,2x1.jpg

    - ./ppm2jpeg --sample=2x2,2x1,2x1 ./images/shaun_the_sheep.ppm --st
    - test -f ./our_test/shaun_the_sheep_2x2,2x1,2x1.jpg

    - ./ppm2jpeg --sample=3x1,3x1,3x1 ./images/shaun_the_sheep.ppm --st
    - test -f ./our_test/shaun_the_sheep_3x1,3x1,3x1.jpg

    - ./ppm2jpeg --sample=3x2,1x2,1x2 ./images/shaun_the_sheep.ppm --st
    - test -f ./our_test/shaun_the_sheep_3x2,1x2,1x2.jpg